{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Functions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "On this lab we will put to practice some of the concepts we have learned on this past few days.\n",
    "\n",
    "`NOTE: On this lab you should try to write all the functions yourself using only the most basic of python syntax and without functions such as len, count, sum, max, min, in, etc. Give it a try. 🧑🏻‍💻👩🏻‍💻`\n",
    "\n",
    "The cell after each exercise contains a few tests to check if your function works as expected."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mod.testing import *\n",
    "import unittest"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Write a function that returns the greater of two numbers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "def greater(a,b):\n",
    "    max_num = 0\n",
    "    \n",
    "    if a > b:\n",
    "        max_num=a\n",
    "    else:\n",
    "        max_num=b\n",
    "    \n",
    "    return max_num"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.134s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greater(greater)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Now write a function that returns the largest element on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "def greatest(arr):\n",
    "    max_arr=0\n",
    "    for i in arr:\n",
    "        if i > max_arr:\n",
    "            max_arr=i\n",
    "    \n",
    "    return max_arr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.163s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greatest(greatest)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Write a function that sums all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sum_all(arr):\n",
    "    sum_all=0\n",
    "    for i in arr:\n",
    "        sum_all=i+sum_all\n",
    "    return sum_all"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.142s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_sum(sum_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Write another function that multiplies all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mult_all(arr):\n",
    "    multi=1\n",
    "    for i in arr:\n",
    "        multi=multi*i\n",
    "    return multi"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.140s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mult(mult_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Now combine those two ideas and write a function that receives a list and either \"+\" or \"*\" and outputs acordingly"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [],
   "source": [
    "def oper_all(arr, oper):\n",
    "    if oper == \"+\":\n",
    "        sum_comb=0\n",
    "        for i in arr:\n",
    "            sum_comb = sum_comb + i\n",
    "        return sum_comb\n",
    "    if oper ==\"*\":\n",
    "        sum_comb =1\n",
    "        for i in arr:\n",
    "            sum_comb = sum_comb * i\n",
    "        return sum_comb\n",
    "    return sum_comb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.150s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_operations(oper_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Write a function that returns the factorial of a number."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [],
   "source": [
    "def factorial(n):\n",
    "    factorial=1\n",
    "    for i in range(1,n+1):\n",
    "        if i <= n:\n",
    "            factorial = factorial*i\n",
    "    return factorial"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.140s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_factorial(factorial)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Write a function that takes a list and returns a list of the unique values.\n",
    "\n",
    "`NOTE: You cannot use set. 🤔`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {},
   "outputs": [],
   "source": [
    "def unique(arr):\n",
    "    lista=[]\n",
    "    for i in arr:\n",
    "        if i not in lista:\n",
    "            lista.append(i)\n",
    "    return lista"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.272s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_unique(unique)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Write a function that returns the mode of a list, i.e.: the element that appears the most times.\n",
    "`NOTE: You should not use count... 🧐`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mode_counter(arr):\n",
    "    \n",
    "    repeticiones = 0\n",
    "    moda = []\n",
    "\n",
    "    for i in arr:\n",
    "        n = arr.count(i)\n",
    "        if n > repeticiones:\n",
    "            repeticiones = n\n",
    "            \n",
    "    for i in arr:\n",
    "        n = arr.count(i) \n",
    "        if n == repeticiones and i not in moda:\n",
    "            moda.append(i)\n",
    "\n",
    "    if len(moda) != len(arr):\n",
    "        return moda"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [11] != 11 : Should be 11\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [11] != 11 : Should be 11\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [13] != 13 : Should be 13\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [19] != 19 : Should be 19\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [16] != 16 : Should be 16\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [4] != 4 : Should be 4\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [16] != 16 : Should be 16\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [11] != 11 : Should be 11\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [4] != 4 : Should be 4\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [12] != 12 : Should be 12\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [18] != 18 : Should be 18\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [9] != 9 : Should be 9\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [18] != 18 : Should be 18\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [25] != 25 : Should be 25\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [7] != 7 : Should be 7\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [13] != 13 : Should be 13\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [18] != 18 : Should be 18\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [5] != 5 : Should be 5\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [9] != 9 : Should be 9\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [20] != 20 : Should be 20\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [12] != 12 : Should be 12\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [21] != 21 : Should be 21\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [14] != 14 : Should be 14\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [8] != 8 : Should be 8\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [22] != 22 : Should be 22\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [7] != 7 : Should be 7\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [17] != 17 : Should be 17\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [7] != 7 : Should be 7\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [18] != 18 : Should be 18\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [5] != 5 : Should be 5\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [4] != 4 : Should be 4\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [20] != 20 : Should be 20\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [24] != 24 : Should be 24\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [3] != 3 : Should be 3\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [16] != 16 : Should be 16\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [25] != 25 : Should be 25\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [22] != 22 : Should be 22\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [10] != 10 : Should be 10\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [17] != 17 : Should be 17\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [7] != 7 : Should be 7\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [13] != 13 : Should be 13\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [15] != 15 : Should be 15\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [15] != 15 : Should be 15\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [25] != 25 : Should be 25\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [11] != 11 : Should be 11\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [7] != 7 : Should be 7\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [16] != 16 : Should be 16\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [13] != 13 : Should be 13\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [10] != 10 : Should be 10\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [3] != 3 : Should be 3\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [7] != 7 : Should be 7\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [12] != 12 : Should be 12\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [11] != 11 : Should be 11\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [6] != 6 : Should be 6\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [14] != 14 : Should be 14\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [3] != 3 : Should be 3\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [18] != 18 : Should be 18\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [22] != 22 : Should be 22\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [25] != 25 : Should be 25\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [9] != 9 : Should be 9\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [13] != 13 : Should be 13\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [8] != 8 : Should be 8\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [9] != 9 : Should be 9\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [2] != 2 : Should be 2\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [4] != 4 : Should be 4\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [3] != 3 : Should be 3\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [2] != 2 : Should be 2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [23] != 23 : Should be 23\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [15] != 15 : Should be 15\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [18] != 18 : Should be 18\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [25] != 25 : Should be 25\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [14] != 14 : Should be 14\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [19] != 19 : Should be 19\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [22] != 22 : Should be 22\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [4] != 4 : Should be 4\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [2] != 2 : Should be 2\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [1] != 1 : Should be 1\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [20] != 20 : Should be 20\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [8] != 8 : Should be 8\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [10] != 10 : Should be 10\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [10] != 10 : Should be 10\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [23] != 23 : Should be 23\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [19] != 19 : Should be 19\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [25] != 25 : Should be 25\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [21] != 21 : Should be 21\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [10] != 10 : Should be 10\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [22] != 22 : Should be 22\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [8] != 8 : Should be 8\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [18] != 18 : Should be 18\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [21] != 21 : Should be 21\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [7] != 7 : Should be 7\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [11] != 11 : Should be 11\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [22] != 22 : Should be 22\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [7] != 7 : Should be 7\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [19] != 19 : Should be 19\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [17] != 17 : Should be 17\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [4] != 4 : Should be 4\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [21] != 21 : Should be 21\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [8] != 8 : Should be 8\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [19] != 19 : Should be 19\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.317s\n",
      "\n",
      "FAILED (failures=100)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mode(mode_counter)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Write a function that calculates the standard deviation of a list.\n",
    "`NOTE: Do not use any libraries or already built functions. 😉`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from statistics import stdev\n",
    "def st_dev(arr):\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_stdev(st_dev)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Write a function to check if a string is a pangram, i.e.: if it contains all the letters of the alphabet at least once. Mind that the strings may contain characters that are not letters."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 101,
   "metadata": {},
   "outputs": [],
   "source": [
    "def pangram(string): #no se como indicar que tenga en cuen\n",
    "    abecedario = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']\n",
    "    minis_string = string.lower()\n",
    "    for i in abecedario:\n",
    "        if i not in minis_string:\n",
    "            pangram = False\n",
    "        else:\n",
    "            pangram = True        \n",
    "    return(pangram)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "................FFFFFF...FF.FF\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: True != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: True != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: True != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: True != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: True != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: True != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: True != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: True != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: True != False : Should be False\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: True != False : Should be False\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 30 tests in 0.056s\n",
      "\n",
      "FAILED (failures=10)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_pangram(pangram)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 11. Write a function that receives a string of comma separated words and returns a string of comma separated words sorted alphabetically.\n",
    "\n",
    "`NOTE: You may use sorted but not split and definitely no join! 🤪`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sort_alpha(string):\n",
    "    return sorted(string)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [854 chars] 'z'] != 'aseclgmzwm,cezsglvut,dnendh,exwcds,fgcjd[136 chars]ziff' : Should be aseclgmzwm,cezsglvut,dnendh,exwcds,fgcjdukg,fzfpxfcbym,houpetuels,jllodvjguj,jmjuxc,kfrs,laua,lflh,lifdy,oxxf,pqda,pvmlwtnwqo,rejhm,rixmjxglt,tvzuiov,wazyanym,ykklhggss,ynmh,zmziff\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', 'b', [224 chars] 'z'] != 'bjjpieqmv,emondq,hykt,ilwkjen,izbdsb,jihfh,nohfc,umgqn' : Should be bjjpieqmv,emondq,hykt,ilwkjen,izbdsb,jihfh,nohfc,umgqn\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [839 chars] 'z'] != 'auzclagiy,bvvjnvz,fhacihb,fylicja,ilpzci[133 chars]yimg' : Should be auzclagiy,bvvjnvz,fhacihb,fylicja,ilpzcittqm,ioco,lvtlaa,mogkpl,msnbeydp,musrllb,pdxt,pyuvdopiuu,qcvwuj,qrvcdya,rkqfz,rnbyiy,shiy,syqxqqyvda,tazttjin,vjjipzecds,ypcwv,yqps,yyimg\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [604 chars] 'z'] != 'auuexcaet,bnqopdh,dmnfxcc,elggrxdyo,ffmv[86 chars]bqvm' : Should be auuexcaet,bnqopdh,dmnfxcc,elggrxdyo,ffmvovii,grgokumgju,mhjp,ogowfqwt,smkc,urhbrxqbiw,xjpd,xmwnwppn,xzwetyuki,ygzz,zpxlusy,zzubqvm\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', 'a', 'b', 'c', 'c', [164 chars] 'z'] != 'cqjleh,gyedy,gzasbhdw,rcekfyveu,rphgfjywvg' : Should be cqjleh,gyedy,gzasbhdw,rcekfyveu,rphgfjywvg\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [684 chars] 'z'] != 'byujbef,bzdbmqyij,danvefajf,fayx,fiolzr,[102 chars]nvjb' : Should be byujbef,bzdbmqyij,danvefajf,fayx,fiolzr,gjfosci,guictyky,gxvtex,hvhu,itsih,moft,qrymsxrsaf,qvwcdzzfe,vdnhymmhsb,zcofrfla,zowhs,ztlybumkr,zyrgcnvjb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [839 chars] 'z'] != 'atiuotn,axccl,dtujgmrkm,exvcwlkatw,ftpps[133 chars]zqox' : Should be atiuotn,axccl,dtujgmrkm,exvcwlkatw,ftppsqdk,gkaaapf,hwfaieka,jhmqk,jjsfvbmmm,kpmso,menhlu,mvomgm,oxvaduatgp,phvmemlvh,pxowudtyah,qhwapqcctz,sdpotwqrkv,uqxkbojpn,wkoatopoul,xzqox\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', 'a', 'a', [204 chars] 'z'] != 'ahiva,gyhohc,hrfgeu,ozsthsgizb,pfmdbj,pploc,zwotwt' : Should be ahiva,gyhohc,hrfgeu,ozsthsgizb,pfmdbj,pploc,zwotwt\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [389 chars] 'z'] != 'bbwukzeesr,dhbag,eymjklxdjc,hcuj,jmjhnmt[43 chars]rbjw' : Should be bbwukzeesr,dhbag,eymjklxdjc,hcuj,jmjhnmtup,kbazntc,lhxz,naga,omnfrvu,sxjtil,uvyi,xcrbjw\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [464 chars] 'z'] != 'abjhzanolm,cnpzgzns,cwez,dfhysgrzeh,ewuc[58 chars]wcve' : Should be abjhzanolm,cnpzgzns,cwez,dfhysgrzeh,ewucv,foqw,gpnrc,jrspxd,ofuhvcnf,pspvz,qtmu,tzcer,urpbzqpe,vmnwcve\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [444 chars] 'z'] != 'cdzbey,halua,jrxldy,jvjr,nlkprlqpfb,oeeg[54 chars]hnbk' : Should be cdzbey,halua,jrxldy,jvjr,nlkprlqpfb,oeeg,poppq,qflazga,qgwitn,sncxef,tkjpqqxgwi,uhkkjxp,uwmbuahnbk\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [639 chars] 'z'] != 'awem,bghlu,blzqo,cnqrdqj,fkvaaf,hngtc,iv[93 chars]sqvr' : Should be awem,bghlu,blzqo,cnqrdqj,fkvaaf,hngtc,ivwdv,kdjzxtmfyk,kwmkiy,lcuesfyvfj,lzzcz,nxpngs,ombm,rshoxsy,rswahxnt,umifr,wmvsux,xznnxvpzk,zlsqvr\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [789 chars] 'z'] != 'fltteg,fpwmwtk,hipqxglyok,ichtobt,klop,l[123 chars]pbrz' : Should be fltteg,fpwmwtk,hipqxglyok,ichtobt,klop,lhqiw,lxtqa,phfstmmxov,rjak,rwbdbfwqnw,sgoypvv,tqysxi,tyqirsbklw,udzxgdk,uhtzyf,uiljosyn,uvuxhsgj,wtsvpmrdo,xgugoilqbw,zuuplpbrz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', 'a', 'a', 'a', 'b', 'b', [129 chars] 'z'] != 'bzjjqad,xhtbztac,xtygkvgj,zvaoldypb' : Should be bzjjqad,xhtbztac,xtygkvgj,zvaoldypb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [674 chars] 'z'] != 'bhxpyt,ckgzviqx,fcufdsmcq,fspyjvmkrg,kmy[100 chars]yyxk' : Should be bhxpyt,ckgzviqx,fcufdsmcq,fspyjvmkrg,kmytn,lgdoqbwind,lqmwfrerdf,mplg,msxtoo,qbyltbqs,qwlt,rmsknx,shcbleaw,tfrzlcmv,uojda,uqngq,wapqqf,wbxvfyyxk\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [359 chars] 'z'] != 'azfysyrgpt,esaxtyh,eypvl,jzvp,lmwcghe,se[37 chars]nijk' : Should be azfysyrgpt,esaxtyh,eypvl,jzvp,lmwcghe,sepheemt,vfwa,wkrptoyg,wqthvbfca,zruqpanijk\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [534 chars] 'z'] != 'ahqu,bgmzkwmlwu,bjfun,dujeucitf,fczjdu,f[72 chars]widn' : Should be ahqu,bgmzkwmlwu,bjfun,dujeucitf,fczjdu,fjkulnqn,fvfckqce,gnnmkxd,gtqywy,htmpmigolj,hzwvbtngl,quftyabe,xmvmvehd,xwidn\n",
      "\n",
      "======================================================================\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', 'b', 'b', 'c', 'd', 'f', [99 chars] 'z'] != 'bxoktb,dismfz,hljurcsqh,lkljn' : Should be bxoktb,dismfz,hljurcsqh,lkljn\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [494 chars] 'z'] != 'cobp,djfztfkft,fwpoxbz,htxqjqevg,kflrmsa[64 chars]yhna' : Should be cobp,djfztfkft,fwpoxbz,htxqjqevg,kflrmsaz,lpuioj,odgptoneuj,oxfyhxcpx,peacixh,psvvm,rgnrjmmg,zlgaoya,zpbyhna\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [674 chars] 'z'] != 'ciahizzwnk,cptgae,drjj,frutfu,jdagno,lpb[100 chars]vpgy' : Should be ciahizzwnk,cptgae,drjj,frutfu,jdagno,lpbur,nkbyyagq,noaj,qtmwiw,qzbd,rkrnhdknc,taim,tjorhs,tlcsjxi,upynhizrc,vrwdcosuo,yceqjkfps,zsff,ztvkrlvpgy\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [649 chars] 'z'] != 'aezt,bygxptmfv,gagshvu,hsisgog,irvm,iwbr[95 chars]iqfy' : Should be aezt,bygxptmfv,gagshvu,hsisgog,irvm,iwbr,jtlyhcbyg,kpnm,mnpwqgif,mtofx,mwvsdtupp,olsehiff,ppulyiplpn,tcrzyq,toiwob,wvpfwyltf,xsyqk,znkxiqfy\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', 'a', 'a', [194 chars] 'y'] != 'diab,exuv,jbwd,ljojgv,ulxbcjhs,uobfurlgnc,yuvyja' : Should be diab,exuv,jbwd,ljojgv,ulxbcjhs,uobfurlgnc,yuvyja\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [744 chars] 'z'] != 'gksxenv,hiwqwtiom,hova,jyuettntza,kavj,k[114 chars]rwpe' : Should be gksxenv,hiwqwtiom,hova,jyuettntza,kavj,kwjrt,kwlrrh,mvddr,pdns,pnyijpud,qltacsg,qtqtsvhpul,ssxedcgdrr,sypen,tosjdv,vnafnedwed,vydeofrn,xdqieo,xmaolickhj,yrwpe\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [599 chars] 'z'] != 'fdghf,gqpaurmtqk,joiaxi,kmvnrjy,lkbdutkz[85 chars]plup' : Should be fdghf,gqpaurmtqk,joiaxi,kmvnrjy,lkbdutkz,oemtdhahwx,ogjfgi,rldatswtk,rqgwivujp,spyvnxclfy,swrtoght,tiggyh,vkaadzyj,yypok,zurtplup\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [314 chars] 'z'] != 'asuq,fxhds,gqguezn,iewmvwikm,jhlriwsg,nu[28 chars]xepm' : Should be asuq,fxhds,gqguezn,iewmvwikm,jhlriwsg,nublvp,qodpaz,utvopkeag,whvon,xepm\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', 'a', 'b', 'b', 'c', [124 chars] 'y'] != 'atwyy,duhtdyr,eiuj,mqdhydyqcl,nbbv' : Should be atwyy,duhtdyr,eiuj,mqdhydyqcl,nbbv\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [854 chars] 'z'] != 'badurrasx,dbaz,efnvh,fjnxwz,gtrkscw,hola[136 chars]jfaz' : Should be badurrasx,dbaz,efnvh,fjnxwz,gtrkscw,holaasfd,jbkswhgnkp,jwqlayx,lrmc,mazjqkiy,nbrdsy,qbukeivojb,qewzxe,saccnqmhdz,teqoy,tjytc,urhuxbpr,uyscvba,wgfgrewknl,xheri,yvnbd,zhdawtz,znjfaz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [854 chars] 'z'] != 'azznbivvjd,bvbeeskz,djswfin,dlpa,dzbmhmd[136 chars]qipu' : Should be azznbivvjd,bvbeeskz,djswfin,dlpa,dzbmhmdq,fwgheens,havwjyac,hbfqlr,nhodggqiz,nibtecpvc,nkktd,ojxxagi,onszvjneem,paajj,powoj,qwhyl,sloz,uvhadj,uyvop,vfwa,xgjgi,xnmbs,xwko,yzujseqipu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [654 chars] 'z'] != 'apfdkpy,cuovyatnlh,elmstl,eripxei,fkczbx[96 chars]ejhh' : Should be apfdkpy,cuovyatnlh,elmstl,eripxei,fkczbxlfh,iqymdgpwn,jmotm,kdqs,ktmbd,lszdkjqshu,mwizcq,onmqkdjf,qyomhhxpbu,rtkzhbttcf,tuumftkwh,ynluumejhh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [934 chars] 'z'] != 'aykzdrccig,cesnurzu,cwkcjjtuq,dcokuhiwk,[152 chars]pvkm' : Should be aykzdrccig,cesnurzu,cwkcjjtuq,dcokuhiwk,ftaisrbh,fyul,gfydkjo,gwlrcbo,kidrfaohhq,labk,lnqcz,nxhrx,pghaz,pjip,pqhjsuqp,pwyyktxw,syqmxusyol,tpctdfhgl,vpiivjtc,wbqze,xggtbt,xlppga,yuvndeifk,zntujpvkm\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [819 chars] 'z'] != 'bdvy,eale,eomxf,gkgfktbik,jpubm,liiq,lom[129 chars]mjzm' : Should be bdvy,eale,eomxf,gkgfktbik,jpubm,liiq,lomgdwxt,ncglfmi,netoinqvzf,neyihuzr,pgdfjvdy,qfgdp,qmdksu,rqrxrlhyt,udelyl,uzobskvlj,vbkgbz,vgpdryewi,vooakq,wkbxco,ygjmo,yuhenjm,zmjzm\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [569 chars] 'z'] != 'cdeunddrqk,dajuzi,exrdxcp,fbflsc,hlnzuix[79 chars]oqtu' : Should be cdeunddrqk,dajuzi,exrdxcp,fbflsc,hlnzuixnjo,iauwjsxuoz,kzlqjffki,mutwxk,vdmh,vijwju,vzlpdzdq,xyvcjdcah,ynsc,yxljzoyz,zeoqtu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [799 chars] 'z'] != 'aplzmgwb,apmbshofy,clyugilc,dcnqxoz,emuo[125 chars]trjb' : Should be aplzmgwb,apmbshofy,clyugilc,dcnqxoz,emuom,esjghipeb,fdgei,fojgldvpoj,pfvkpwhd,qggido,qzrrneuty,sduuhot,srpmb,taan,ukoela,urypdzir,uxdw,vmccd,wexisqnc,wttvew,xnkdwg,ytrjb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', 'a', 'a', 'b', 'e', [144 chars] 'y'] != 'fvmqio,nyppyxqak,phjup,sjatre,utnfeklb' : Should be fvmqio,nyppyxqak,phjup,sjatre,utnfeklb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [319 chars] 'z'] != 'ceddjq,cqzyfz,elrhegteqz,ibfimx,olactwgw[29 chars]lmrp' : Should be ceddjq,cqzyfz,elrhegteqz,ibfimx,olactwgw,prowkvoy,qtzflfm,sewpy,srqrjlmrp\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [814 chars] 'z'] != 'bcin,bcrd,bddhn,blbofz,chemsi,crujkadrh,[128 chars]hqqm' : Should be bcin,bcrd,bddhn,blbofz,chemsi,crujkadrh,dizg,dlybrg,dlykekcyh,eqtaxtpco,fefwnoj,gsce,igyu,iqioeg,kdjulh,keygcaa,kipimg,liacmeitvh,lrelslnc,mhyrjpgpkd,pxefyotz,vvhmv,yaqhqqm\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [844 chars] 'z'] != 'acutrj,cfxtiegc,fetjxhfzc,hpehv,jqcyyxag[134 chars]bxhs' : Should be acutrj,cfxtiegc,fetjxhfzc,hpehv,jqcyyxagpq,kgkqwql,lfykqr,lvsvkbmoxk,qutp,qyzsyc,rnqoeinb,sczjwvvdqa,srgawxygok,szsjupsfk,whvgeninz,wrmmdrqx,xazqmnuugo,xotpwxzewp,yktqp,znpuebxhs\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', 'a', 'b', 'b', 'd', [154 chars] 'z'] != 'gaixzjxdku,kovvilti,nlkvdyfdh,rghub,ygob' : Should be gaixzjxdku,kovvilti,nlkvdyfdh,rghub,ygob\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [709 chars] 'z'] != 'abfjmutr,afri,ayjqtunurd,eitn,fcyi,ibipx[107 chars]rxmq' : Should be abfjmutr,afri,ayjqtunurd,eitn,fcyi,ibipxvr,icrxhxgy,ixokxztglb,jivkz,joggy,jsklxlil,mhhuxpvy,nhxfvhk,pgpn,polug,rcyqm,soejc,sytchjba,vxqv,xhjtyge,xrxmq\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', 'a', [219 chars] 'z'] != 'azvynitnto,ccemvsf,dsdjsir,hgyy,ommrbi,pcgc,rvow,tduf' : Should be azvynitnto,ccemvsf,dsdjsir,hgyy,ommrbi,pcgc,rvow,tduf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [804 chars] 'z'] != 'gopxllmpo,grkle,gtwinnv,hbksjlddl,hxgih,[126 chars]gmij' : Should be gopxllmpo,grkle,gtwinnv,hbksjlddl,hxgih,jznpgozfpt,kklaygk,lkfwcf,mybjfu,ocsi,pkmpz,pwtmwu,qaizrvbkn,qvzbdhz,qxkvvqsd,sasi,sefebutif,svltsqu,ubwog,xzmskgumrw,yssfd,zxgmij\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [619 chars] 'z'] != 'bknjaqemg,bxwkzbc,cfhc,gazc,gupype,hfphq[89 chars]jjzs' : Should be bknjaqemg,bxwkzbc,cfhc,gazc,gupype,hfphq,hhrpjwxpgq,iygldruian,nsplv,pirslad,qbwqpt,qgbq,rgpyw,tlinmwd,tznzbt,uppkuh,vbygh,voko,wjjzs\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', 'a', 'a', [214 chars] 'y'] != 'atfnicbw,dvasurr,ffudxikb,shbfv,vklfvoww,xcyag,xwgbw' : Should be atfnicbw,dvasurr,ffudxikb,shbfv,vklfvoww,xcyag,xwgbw\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [484 chars] 'z'] != 'bcuqke,cnadhtwg,eyvpevmwwu,ezzqrm,fbwt,j[62 chars]qvqq' : Should be bcuqke,cnadhtwg,eyvpevmwwu,ezzqrm,fbwt,jcgx,kbrjhtnqqx,kezbq,mlexid,nacywpcrhs,qdbqk,vrhsm,zmtkmny,zzhqvqq\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [804 chars] 'z'] != 'aietgk,apaf,bzay,ctczqv,ctubk,cznth,dbsy[126 chars]dftm' : Should be aietgk,apaf,bzay,ctczqv,ctubk,cznth,dbsyamra,eawpp,epcmffb,evzcwswjr,exmjnzaihz,exmyx,icwwarq,jqcgfkulm,latju,lyte,okuyaxlhwa,oyjt,qppyovosm,rodvh,stzsivq,vrpfpoio,wzdftm\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', 'b', 'c', 'd', 'd', [114 chars] 'z'] != 'cddlz,dlkeo,hnhvt,rehnbz,tvfyhnd' : Should be cddlz,dlkeo,hnhvt,rehnbz,tvfyhnd\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [284 chars] 'z'] != 'ezdquyzp,hwkhh,hywxsvacka,nnko,qyvbnpwc,[22 chars]jbcs' : Should be ezdquyzp,hwkhh,hywxsvacka,nnko,qyvbnpwc,ravs,urjy,vfmcsaty,ydmjbcs\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [744 chars] 'z'] != 'cvxtnhy,dlen,dmqojldmue,egum,grtsvu,ictn[114 chars]pvbm' : Should be cvxtnhy,dlen,dmqojldmue,egum,grtsvu,ictn,mhet,mtklj,nulmiztsho,oqoiupv,splezuksij,tfogvzapq,thknrmgy,tzukebubat,vnspfcx,wkzktc,wpenj,xdyfcaxrvm,yhzagq,zlfpvbm\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [279 chars] 'z'] != 'nahght,nvtz,pdrqqaxvrd,pdwquuvmbx,qpftnj[21 chars]bclb' : Should be nahght,nvtz,pdrqqaxvrd,pdwquuvmbx,qpftnjc,rdwd,rnyt,vunkffl,zbclb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [1014 chars] 'z'] != 'ahhymifkgf,axrjmuov,bzcmnkerrj,ccqirlnbn[168 chars]xlus' : Should be ahhymifkgf,axrjmuov,bzcmnkerrj,ccqirlnbn,cjhdtuk,cmyydmsely,dxqs,elqfa,exiu,fntvycf,hiulzo,hybpodvcgo,jfrmgfdah,jlfxvr,mopgkhch,pbbdufnn,qdiutbf,qndyjww,rjpxamp,utrfg,xvwtmhss,yayoh,yfkadsoxro,ztcqmnyw,zzsmmrxlus\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [834 chars] 'z'] != 'bift,bomiqakes,cauyaogofi,cblhddsg,fppzy[132 chars]cebp' : Should be bift,bomiqakes,cauyaogofi,cblhddsg,fppzynw,gilwl,grgpgl,mejgbhyisg,nycadcdy,oyykmdtsg,qmfm,qvmon,sjsipjfqfo,togllgdx,ujugpbvmi,uswp,vfouvvaye,yhtsujzv,yonpnhq,zfzowlden,zlscebp\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [664 chars] 'z'] != 'bnluzn,eklhvyp,fnuus,fsqqj,gcwi,gvcv,ibq[98 chars]rwxi' : Should be bnluzn,eklhvyp,fnuus,fsqqj,gcwi,gvcv,ibqce,klntrsugbo,lgmqfo,lvpiucg,miruwfq,nkdjtaexzd,nxucatlny,omion,vmovzww,xflaltvml,xkhefzflo,zcpfzfrwxi\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [969 chars] 'z'] != 'adcv,bysps,cssmvqgys,cwyt,ddgqpxz,dgwzfi[159 chars]ovwm' : Should be adcv,bysps,cssmvqgys,cwyt,ddgqpxz,dgwzfivba,djmzh,fvjpuoxx,gcgbhsdwix,ggqjygk,grzjsyk,hmepwbtes,jqqzowszaq,mapegbezde,nrjvvhxxxu,phxjzdqku,rbcg,rbjfzzxjy,remb,rfivbehkp,rqluf,selgtj,shlbykye,tfup,tvbovwm\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [594 chars] 'z'] != 'cgvpyvn,dhygoaibss,dzxfl,etxharehs,gsmp,[84 chars]gysh' : Should be cgvpyvn,dhygoaibss,dzxfl,etxharehs,gsmp,hhkg,hkmra,jdhvp,madwk,odaqelq,qtcucbkio,tacjurnfrj,uhjvlnwsyk,ukmqdos,utxxzq,vtnj,ygysh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', 'a', 'b', 'c', [189 chars] 'y'] != 'bcokrc,eiaxqqmhk,jmlfwvec,wtsi,wxuwyfdulh,ycsfi' : Should be bcokrc,eiaxqqmhk,jmlfwvec,wtsi,wxuwyfdulh,ycsfi\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [794 chars] 'z'] != 'afreu,cgraojuu,cshk,cupohgm,cywzrckzf,do[124 chars]zbvi' : Should be afreu,cgraojuu,cshk,cupohgm,cywzrckzf,dohm,dpzl,fejaowgohk,fkph,fvvo,jrlzn,jupya,liaoijkihf,mhueyzsa,mikax,mpxndy,nbkmsjcg,roowqdhdb,rqfojgtm,scrv,wfcgh,xvauf,yctvozbvi\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [684 chars] 'z'] != 'czxrejsvbe,ddlxbx,dgatuuha,gqze,hsaxrk,i[102 chars]tinw' : Should be czxrejsvbe,ddlxbx,dgatuuha,gqze,hsaxrk,igto,ixxsu,mmlwb,nitxbnewkf,ouvp,pjjfbhdm,plrqvabm,prhaoek,scxpwa,sicmo,suatxngyc,waejj,wnqq,xuwtdgt,ymtinw\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [894 chars] 'z'] != 'aixiz,amlwv,cmbdkyjph,dphoemqqer,eobsj,g[144 chars]kchu' : Should be aixiz,amlwv,cmbdkyjph,dphoemqqer,eobsj,gthgykhb,ijyo,irkzfixx,jlzgwgm,livyjics,onfdb,ooie,opcq,ovwvjcjz,pfaao,qfnnndlyi,qrqvyyk,whowkmjuo,xdjbixt,xhdjgjev,ygwlgal,yowldz,zhvhvmwjqf,zpxkchu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [819 chars] 'z'] != 'axgnv,bagbbdyoto,cuvkaq,dpssssc,fmyyf,gc[129 chars]wolh' : Should be axgnv,bagbbdyoto,cuvkaq,dpssssc,fmyyf,gcfdujpbz,hjihtlu,iyhcurf,kkrn,knbfsnh,mircfeygqg,nhbtsgcryz,nwyozbpfj,oqekhasjh,qlyyswjhor,rmcvylbzsq,rwywkosjft,tsyjk,utlh,wblyn,wolh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [919 chars] 'z'] != 'bsmpyokba,cekvyjj,cggzrptz,cgldueow,esjp[149 chars]ztxh' : Should be bsmpyokba,cekvyjj,cggzrptz,cgldueow,esjpg,gwfncoo,iety,iqvgnowqw,ivqaunjttt,jqsiefra,ktzdykovc,mkkqvboda,mvafcdvaiw,nfrbs,nkhx,okyzq,qjqtfqgo,qsmzc,rvgna,tdlarqqbx,tidqriyz,tzfcg,xbxqu,yidrztxh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [399 chars] 'z'] != 'efjzvrxaom,hlgr,hqttfx,kppzgzlu,mfeiztiw[45 chars]egpg' : Should be efjzvrxaom,hlgr,hqttfx,kppzgzlu,mfeiztiwrc,owsxhrz,uttbcykbmo,vkbxdfr,xdhdz,xtnxgnm,yegpg\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [579 chars] 'z'] != 'amrvasvpjm,bgoaj,clevxhyh,fzfcuvt,jkyesu[81 chars]spbf' : Should be amrvasvpjm,bgoaj,clevxhyh,fzfcuvt,jkyesumqw,jltspf,knqi,mcvvwncar,nysngx,qbrobhd,qjzti,teqn,wktpsp,xwrtlem,zefzcmbvgk,zquspbf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [494 chars] 'z'] != 'bzdm,dmmtz,emget,gbnd,hkycwp,kwqxynnhpm,[64 chars]zcno' : Should be bzdm,dmmtz,emget,gbnd,hkycwp,kwqxynnhpm,mfqcn,rhlyadksy,soiyuajemw,tlwgs,tzqexmwibl,vcanxkabpn,wqxdnbfz,zcno\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [829 chars] 'z'] != 'aalnzfg,ahjtpfq,asvat,awntob,bmkrgdpo,bn[131 chars]owul' : Should be aalnzfg,ahjtpfq,asvat,awntob,bmkrgdpo,bndp,civlrlj,cqgore,cvuqs,dxsusy,etleknm,hljlbwasik,hlonwa,hxarjtfb,jezfzdtln,jlsknttrld,lcsvguqpvs,mcqwgytle,sgog,vvmp,xszuze,zestunowul\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [654 chars] 'z'] != 'idsrp,ijvvjgvxgv,lgzkvslnx,mnwzoopcsz,nq[96 chars]zsje' : Should be idsrp,ijvvjgvxgv,lgzkvslnx,mnwzoopcsz,nqwttkoexi,pdlem,qlsz,qvdspu,rixabnb,ryxgyn,sedbg,tdcywxwpt,tdeyaw,vgqqr,vxttzocnmt,yonqmc,ywqyvn,zsje\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [809 chars] 'z'] != 'alzauiwx,aqibpoyhgq,azawal,bdgvhu,bgrbqt[127 chars]emis' : Should be alzauiwx,aqibpoyhgq,azawal,bdgvhu,bgrbqt,efbir,hakml,hvxsah,jclhrjo,lkhla,lopdxtdm,mqazilmhpy,pzqqrvqycb,qgcufxakw,tdmk,vnybzugvve,xehtfqy,xpsvuc,xrutrlm,xtktxe,zswhwhemis\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', 'a', 'a', [259 chars] 'z'] != 'jgpubfplwq,lvgzhjvbk,mkrliqbabb,oylhdryp[17 chars]zldp' : Should be jgpubfplwq,lvgzhjvbk,mkrliqbabb,oylhdryp,vamxg,yroaodxua,zldp\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [749 chars] 'z'] != 'beldmyw,bwtyuhmbga,cwrl,eahfbkm,fucr,fvo[115 chars]rzsq' : Should be beldmyw,bwtyuhmbga,cwrl,eahfbkm,fucr,fvouqzwpkb,gcguyy,kafzobxgz,kktg,kucl,meqfxighw,mxgrdcaxck,ncsb,nruforq,onvhvinnlp,qcabe,rvtm,vwrzilav,yheslphp,yodhufrzsq\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [939 chars] 'z'] != 'anihan,csmfezlshl,ejtzuk,gbqimhjwvx,gfta[153 chars]zytd' : Should be anihan,csmfezlshl,ejtzuk,gbqimhjwvx,gftanfqoq,gordxllxu,hhiggbdrqp,hiqca,izorqv,kbyeks,kvenmc,lfpoywbor,mdnwc,ncotjr,ohbhfm,pqidfujdpy,rkwf,sagxdsf,scnwuqwhar,senk,syxi,vdgokvse,vrseoqknl,ylyh,zytd\n",
      "\n",
      "======================================================================\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [514 chars] 'z'] != 'aaqoc,aydfwj,cgpxi,cwki,dzmef,earlv,kaey[68 chars]irbc' : Should be aaqoc,aydfwj,cgpxi,cwki,dzmef,earlv,kaeyfzmjme,kgbpnyp,kqllvapbv,ktqlqgru,mycmo,nlnc,nqpbr,tecdqfgr,twor,uaairbc\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [314 chars] 'z'] != 'gxnqwibavc,iwxwisy,jcmatxyxjp,jjxdifj,lr[28 chars]waac' : Should be gxnqwibavc,iwxwisy,jcmatxyxjp,jjxdifj,lrpje,taby,vnytpal,yovi,zqwhrgwaac\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [484 chars] 'z'] != 'btxjjtfay,detcva,epbxntt,hlyvmp,ijgfppg,[62 chars]zrhs' : Should be btxjjtfay,detcva,epbxntt,hlyvmp,ijgfppg,kcwaoh,njpkecth,onlot,pbdxco,qjlehdgvef,rxynxpg,tfpr,zhmhfdhd,zrhs\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [324 chars] 'z'] != 'fydavu,ggbvaer,goxl,kxwwcraav,sciinbsyz,[30 chars]juwk' : Should be fydavu,ggbvaer,goxl,kxwwcraav,sciinbsyz,voyxstbdo,xhyovw,yetqwwh,zfowzjuwk\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [499 chars] 'z'] != 'ayfwzfr,cnalnlb,cnntcuvdjb,cpem,mnlb,mym[65 chars]fhyl' : Should be ayfwzfr,cnalnlb,cnntcuvdjb,cpem,mnlb,mymwwpelmu,owgibdyif,qcpfxct,rdikjaki,wkaaxjuc,wqdt,xllxnyiatr,ynzdjfhyl\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [504 chars] 'z'] != 'bekqdpdfhm,cwjck,hmhywt,inwq,mfvezdnfey,[66 chars]agqu' : Should be bekqdpdfhm,cwjck,hmhywt,inwq,mfvezdnfey,muxu,npyhoghfm,osqszuto,urtna,vssrhscld,vwxjhdfdzr,yonxnutdtw,zfmkagqu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [544 chars] 'y'] != 'dtrox,ehyreqgw,eqsygalh,gdgvlpk,iakyrwlx[74 chars]qfwn' : Should be dtrox,ehyreqgw,eqsygalh,gdgvlpk,iakyrwlxm,jfswcvvvf,msfn,mver,ntvipcby,pxyh,vqbwajwdkb,watfxtxtt,wklm,yrcaxj,yvybfqfwn\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [439 chars] 'z'] != 'axfbdnsnv,bxxcv,eisbpjkmp,fsxpah,hzcvr,j[53 chars]ddhi' : Should be axfbdnsnv,bxxcv,eisbpjkmp,fsxpah,hzcvr,jhgqytrt,oztuiduat,pjnfenvc,spivuvzgc,tjmibnrrcy,unjdnddhi\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', 'a', 'a', 'b', 'b', 'c', [114 chars] 'y'] != 'bkcvjdgnj,jbar,nquragigh,oeljsyp' : Should be bkcvjdgnj,jbar,nquragigh,oeljsyp\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [444 chars] 'z'] != 'aqhbfjrbe,ayuq,dwoikttbr,gaxcbc,gkxnqkyy[54 chars]zmzi' : Should be aqhbfjrbe,ayuq,dwoikttbr,gaxcbc,gkxnqkyyas,gpqyn,hfsglsxys,kyypt,orcn,trvsney,utvqwicwyw,zizp,zmzi\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', 'a', 'a', 'c', [159 chars] 'y'] != 'ddkyosa,dexkor,jahceifk,qsvk,rjxy,wiqomtt' : Should be ddkyosa,dexkor,jahceifk,qsvk,rjxy,wiqomtt\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [879 chars] 'z'] != 'akfsokat,aoxndyls,ashbnrlftz,cvwayfg,ded[141 chars]jwev' : Should be akfsokat,aoxndyls,ashbnrlftz,cvwayfg,dedrqdx,dsltr,ihgjm,iwiic,iydwc,kjqeg,lqozoqpp,mjjiyjr,nsbtwvg,rcrhvxupas,sxhpbkdt,sxkkg,tlythcfq,xhilhrae,yakltz,youjyea,yuaz,yyeiso,zmxc,zwbngjwev\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [439 chars] 'z'] != 'bvkyvs,cxfluvjcjn,fkjc,gpylag,itds,jgaht[53 chars]udir' : Should be bvkyvs,cxfluvjcjn,fkjc,gpylag,itds,jgahtm,jksllhltq,jlnzipmarz,juhst,qrbobj,salwbqqh,ssrfrfy,udir\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [779 chars] 'z'] != 'bnrxdeyjcz,cjfcgy,eapaibm,eyrfok,flihth,[121 chars]odmm' : Should be bnrxdeyjcz,cjfcgy,eapaibm,eyrfok,flihth,ijfjjjxw,isitmgm,ixumsuysz,jmarhlwwzn,mquwmdb,nmbouepl,sejfxnpaie,stkoyjyoe,ugqxmxufno,uwrvaqbye,wctozbgc,xcwoqiywpa,xgrxodmm\n",
      "\n",
      "======================================================================\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [719 chars] 'z'] != 'ahgfwfa,bbhok,bqdrwquw,bszg,lqyrexh,mctv[109 chars]pccx' : Should be ahgfwfa,bbhok,bqdrwquw,bszg,lqyrexh,mctvalz,mwjpbil,oyfbqizcir,petw,qsluoibn,rbnypmbjd,rpzgier,tgnw,wswquihk,xnnphzg,ykdflws,yqoypwouk,yxgasmys,zjnvmpccx\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [749 chars] 'z'] != 'ddqawncq,eapuo,fewuvcn,gexwv,haabfx,hhom[115 chars]joji' : Should be ddqawncq,eapuo,fewuvcn,gexwv,haabfx,hhomr,hilbitunmr,kxtfwomrm,lvrwgnqimj,mksnxrmsv,nbfxqinntg,nhtnkqdc,ntzho,qipifknjqt,udpwjja,vbrsyos,vlyug,xixwqizbr,zxjoji\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', 'a', 'b', 'b', 'c', 'c', [124 chars] 'z'] != 'azjkxvofkz,bhbdzp,ocekckdf,okougir' : Should be azjkxvofkz,bhbdzp,ocekckdf,okougir\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [764 chars] 'z'] != 'abjxn,blitvozg,cxqixfmv,dssfduc,fidrrnuc[118 chars]tdho' : Should be abjxn,blitvozg,cxqixfmv,dssfduc,fidrrnuc,fnagyawuo,hanh,hcyd,mzda,nepwqu,pcikvt,pqwanjsmq,punhn,qmeymraan,rdvb,sasvl,tgphmdf,ulwen,vetxamt,wrwujasup,yjdyisy,ztdho\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [424 chars] 'z'] != 'aqub,fpmacbpwy,gbvkk,gqzhumxqdw,kjxvnjzw[50 chars]wdhy' : Should be aqub,fpmacbpwy,gbvkk,gqzhumxqdw,kjxvnjzwev,ksikun,ntykj,pssggw,pyxd,wtgqc,xnlsvcnxrx,xonuqwdhy\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [739 chars] 'z'] != 'bhemvpgcyh,bpvqpgi,caqvm,chiwcokj,cpyygs[113 chars]toau' : Should be bhemvpgcyh,bpvqpgi,caqvm,chiwcokj,cpyygs,dkvlrajvui,efhvinjtsc,fccn,ffqyx,gjpew,jpxxetj,kcaoql,mqocnxv,nlosps,nmqzt,ntnusxkimi,osqjyrt,rmqwv,vjtkrjizqv,ztoau\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [669 chars] 'z'] != 'beynwt,cacdprfxq,cyczohz,fghzmmisv,gpdct[99 chars]ykrg' : Should be beynwt,cacdprfxq,cyczohz,fghzmmisv,gpdctgyl,gtwft,hzjpipxyiz,imdi,owsur,rdhoux,rnee,satq,sgefat,syvmi,tvgkus,whir,wlndolxhze,xasjtida,zcvfmykrg\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [564 chars] 'z'] != 'aeuegwq,avaa,bpasmby,ctey,dvgixwnfdw,fdx[78 chars]egsj' : Should be aeuegwq,avaa,bpasmby,ctey,dvgixwnfdw,fdxuahlqgu,fgzdmc,ftex,gspxr,hvpzqcznl,linwgm,mkonxq,oyhmf,ugqcrya,zrgnzxyja,zrvnegsj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [634 chars] 'z'] != 'bmraa,bsfxnfzeob,eylgigg,fanekonvc,fmpdt[92 chars]kuyv' : Should be bmraa,bsfxnfzeob,eylgigg,fanekonvc,fmpdtc,gknrccsjyo,imjlubjms,jqxobt,mivmxqkkge,nbywkn,nlrbfo,pnnyffhyy,xfbst,xftyissg,ylduqaen,zwikuyv\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', 'a', 'c', 'c', 'd', 'd', [134 chars] 'z'] != 'eckoxqkwtc,pfzadtxse,xkjqdroj,zwkfjh' : Should be eckoxqkwtc,pfzadtxse,xkjqdroj,zwkfjh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [419 chars] 'z'] != 'dqdbb,dxepb,ewkszu,jddtvll,lxcwcbf,pseen[49 chars]vzqj' : Should be dqdbb,dxepb,ewkszu,jddtvll,lxcwcbf,pseenyk,qfbtretus,qllekyhgcw,skbsjjjdva,viswdlzb,vttj,vzqj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', 'a', 'b', 'b', [189 chars] 'z'] != 'fakyxqw,nxdhydypuc,qeqf,trxvbvjrg,ukkd,ztcfbzut' : Should be fakyxqw,nxdhydypuc,qeqf,trxvbvjrg,ukkd,ztcfbzut\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [354 chars] 'z'] != 'berbnh,gdav,jvuich,mlmidbvvd,rdjavpru,rr[36 chars]zjpl' : Should be berbnh,gdav,jvuich,mlmidbvvd,rdjavpru,rrzb,sgmu,shazmwqgxz,teqrjwz,zues,zzatzjpl\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', 'a', 'a', [224 chars] 'z'] != 'cqtadizf,ipsqs,mvvmvru,pgeqtbi,pxunby,qlrpai,ztumrdmjk' : Should be cqtadizf,ipsqs,mvvmvru,pgeqtbi,pxunby,qlrpai,ztumrdmjk\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [914 chars] 'z'] != 'becabn,cfngwazy,fysni,gjlbcbr,gkooivqok,[148 chars]pkdu' : Should be becabn,cfngwazy,fysni,gjlbcbr,gkooivqok,ikrr,iqjk,jadquilns,kbyqt,llvcnujy,miqryyms,mitcqnpi,nzztuxby,pemrhnjqg,psiifwf,qngsrowc,tgmyp,uvucdjoh,xvzsar,ymxkh,yuxzmtidv,yyhaaht,zjerloug,zrsqpkdu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [764 chars] 'z'] != 'atmdpwbg,bcwncrimo,dttus,fbqfcbiu,fgsf,f[118 chars]wgfb' : Should be atmdpwbg,bcwncrimo,dttus,fbqfcbiu,fgsf,fjwaa,jasufg,kdxg,lsngnpvxt,mkeuxet,nvdtafxdsl,obaeqzpy,ojrl,osboak,pbeen,qsuuaasu,sslijabgxo,vtvjwai,vvsvt,wnnua,zpsguwgfb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/c/Users/34687/documents/github/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', 'a', 'a', 'b', [159 chars] 'z'] != 'axkvudkv,bjkxvjmw,chlhte,cvtu,sqosa,vzvzg' : Should be axkvudkv,bjkxvjmw,chlhte,cvtu,sqosa,vzvzg\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.208s\n",
      "\n",
      "FAILED (failures=100)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_alpha(sort_alpha)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 12. Write a function to check if a given password is strong (at least 8 characters, at least one lower case, at least one upper case, at least one number and at least one special character). It should output True if strong and False if not.\n",
    "`Valid special characters: # @ ! $ % & ( ) ^ * [ ] { }`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def check_pass(string):\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_pass(check_pass)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
